name: Run Script

on: 
  workflow_dispatch:
    inputs:
      businesstype:
        description: Select the type of business you would like to search for
        default: cafe
        required: true
        type: string
      userinput_address:
        description: Enter your street address and postal code (i.e. 123 Happy Street 45678) 
        required: true
        type: string
      userinput_radius:
        description: Enter the radius to search in miles (Up to 30) 
        required: true
        type: string
      userinput_apikey:
        description: Enter your Google Maps API key here 
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pandas
      - run: python3 nearbybusinesses.py