name: Run Script

on: workflow_call
  inputs:
    businesstype:
      description: 'The type of business you would like to search for'
      default: 'cafe'
      required: false
      type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pandas
      - run: python3 nearbybusinesses.py
