name: Run Script

on: 
  workflow_dispatch:
    inputs:
      businesstype:
        description: Select the type of business you would like to search for
        default: cafe
        required: true
        type: string
      userinput_address:
        description: Enter your street address and postal code (i.e. 123 Happy Street 45678) 
        required: true
        type: string
      userinput_radius:
        description: Enter the radius to search in miles (Up to 30) 
        required: true
        type: string
      google_api_key: ${{ secrets.GOOGLE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pandas
      - run: |
          echo "type: ${{ github.event.inputs.businesstype }}"
          echo "address: ${{ github.event.inputs.userinput_address }}"
          echo "radius: ${{ github.event.inputs.userinput_radius }}"
          BUSINESS_TYPE="${{ github.event.inputs.businesstype }}" ADDRESS="${{ github.event.inputs.userinput_address }}" RADIUS="${{ github.event.inputs.userinput_radius }}" APIKEY="${{ github.event.inputs.google_api_key }}" python3 nearbybusinesses.py
      - uses: actions/upload-artifact@v3
        with:
          name: businesses-output
          path: output.csv